"use client";
import { useEffect, useRef, useState } from "react";
import { audioUrl, books, type Book, volumeLinks } from "./audio-manifest";

const movements = [["The Telemachy", "Books 1–4"], ["The Homecoming", "Books 5–8"], ["The Great Wanderings", "Books 9–12"], ["Ithaca", "Books 13–24"]] as const;

export default function Home() {
  const [currentBook, setCurrentBook] = useState<Book>(books[0]);
  const [isPlaying, setIsPlaying] = useState(false); const [progress, setProgress] = useState(0); const [duration, setDuration] = useState(0); const [showGuide, setShowGuide] = useState(false);
  const player = useRef<HTMLAudioElement>(null); const source = audioUrl(currentBook);
  useEffect(() => { setIsPlaying(false); setProgress(0); setDuration(0); }, [currentBook]);
  const seek = (value: number) => { if (player.current && duration) { player.current.currentTime = value; setProgress(value); } };
  const play = async () => { if (!source || !player.current) return; if (isPlaying) player.current.pause(); else await player.current.play(); };
  const formatTime = (seconds: number) => `${Math.floor(seconds / 60)}:${String(Math.floor(seconds % 60)).padStart(2, "0")}`;
  const selectBook = (book: Book) => { setCurrentBook(book); window.setTimeout(() => document.getElementById("listen")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); };
  return <main>
    <header className="masthead"><a className="wordmark" href="#top">THE ODYSSEY <span>in English hexameter</span></a><nav><a href="#listen">Listen</a><a href="#books">Books</a><button onClick={() => setShowGuide(true)}>About the meter</button></nav></header>
    <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow">A listening edition</p><h1>Hear the journey<br /><em>line by line.</em></h1><p className="intro">Homer’s <i>Odyssey</i>, newly rendered in an English analogue of dactylic hexameter: twenty-four books, one English verse for every Greek verse.</p><div className="hero-actions"><button className="primary" onClick={() => selectBook(books[0])}>Begin with Book 1 <span>→</span></button><a className="quiet-link" href="#books">Browse all twenty-four books</a></div></div><div className="hero-mark" aria-hidden="true"><div className="sun-disc" /><div className="wave one" /><div className="wave two" /><div className="wave three" /><p>— u u &nbsp; — u u<br />— u u &nbsp; — u u<br />— u u &nbsp; — x</p></div></section>
    <section className="movement-strip">{movements.map(([name, range], index) => <a key={name} href={`#movement-${index + 1}`}><b>0{index + 1}</b><span>{name}</span><small>{range}</small></a>)}</section>
    <section id="listen" className="listening-room"><div className="section-heading"><p className="eyebrow">Now listening</p><p className="counter">BOOK {String(currentBook.number).padStart(2, "0")} / 24</p></div><div className="player-card"><div className="player-copy"><h2>{currentBook.title}</h2><p>{currentBook.summary}</p><p className="line-count">{currentBook.lines} verses · English hexameter</p></div><div className="controls"><button className="skip" onClick={() => seek(Math.max(progress - 15, 0))} disabled={!source}>↺<small>15</small></button><button className="play" onClick={play} disabled={!source}>{isPlaying ? "Ⅱ" : "▶"}</button><button className="skip" onClick={() => seek(Math.min(progress + 15, duration))} disabled={!source}>↻<small>15</small></button></div><div className="timeline"><span>{formatTime(progress)}</span><input aria-label="Playback position" type="range" min="0" max={duration || 1} value={progress} onChange={(event) => seek(Number(event.target.value))} disabled={!source} /><span>{duration ? formatTime(duration) : "—:—"}</span></div>{source ? <audio ref={player} src={source} preload="metadata" onPlay={() => setIsPlaying(true)} onPause={() => setIsPlaying(false)} onTimeUpdate={(event) => setProgress(event.currentTarget.currentTime)} onLoadedMetadata={(event) => setDuration(event.currentTarget.duration)} onEnded={() => setIsPlaying(false)} /> : <p className="release-note">The final narration is being prepared. The player will activate as soon as its public audio address is connected.</p>}</div><div className="volume-links"><div><p className="eyebrow">Continuous listening</p><p>Long-form volumes open in the archive.</p></div><div>{volumeLinks.map((volume) => volume.url ? <a key={volume.title} href={volume.url} target="_blank" rel="noreferrer"><span>{volume.books}</span>{volume.title} <b>↗</b></a> : <span className="volume-pending" key={volume.title}><span>{volume.books}</span>{volume.title}</span>)}</div></div></section>
    <section className="reader-introduction"><p className="eyebrow">How to listen</p><div><h2>Not a translation to skim,<br />but a measure to hear.</h2><p>Each line has six falling beats. The page begins in the clean reading text; the companion performance text preserves the stresses, feet, and pronunciation cues behind the audible line.</p></div></section>
    <section id="books" className="book-list"><div className="book-list-heading"><p className="eyebrow">The complete poem</p><h2>Choose a book</h2></div>{movements.map(([movement, range], index) => <div key={movement} id={`movement-${index + 1}`} className="movement"><div className="movement-label"><b>0{index + 1}</b><div><h3>{movement}</h3><p>{range}</p></div></div><div className="book-grid">{books.filter((book) => book.movement === movement).map((book) => <button key={book.number} className={book.number === currentBook.number ? "book-card active" : "book-card"} onClick={() => selectBook(book)}><span>BOOK {String(book.number).padStart(2, "0")}</span><h4>{book.title}</h4><p>{book.summary}</p><small>{book.lines} verses <i>→</i></small></button>)}</div></div>)}</section>
    <footer><p>THE ODYSSEY IN ENGLISH HEXAMETER</p><p>A continuing translation and listening project.</p><button onClick={() => setShowGuide(true)}>About the meter</button></footer>
    {showGuide && <div className="modal-backdrop" onMouseDown={() => setShowGuide(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="meter-title" onMouseDown={(event) => event.stopPropagation()}><button className="close" onClick={() => setShowGuide(false)} aria-label="Close">×</button><p className="eyebrow">The metrical approach</p><h2 id="meter-title">Six falling beats in English</h2><p>Homer’s dactylic hexameter is quantitative; this translation uses stress as its audible principle. Dactylic feet predominate, with contracted feet and spondaic weight where the line calls for them.</p><pre>— u u | — u u | — u u | — u u | — u u | — x</pre><p>The governing pattern is an accentual counterpart to Homeric hexameter—not a claim that English reproduces ancient Greek vowel length.</p></section></div>}
  </main>;
}
